[project]
name = "tft-spot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Daniel Morawski", email = "gvrmvnn@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.116",
    "polars>=1.44.1",
    "pydantic>=2.13.5",
    "uvicorn[standard]>=0.35",
]

[project.scripts]
tft-spot = "tft_spot:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "ruff>=0.16.6",
]
